import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { TimelineItem } from '../services/dataStore';

/**
 * Exports the Event Timeline to a styled PDF
 */
let isSharing =false; 
export const exportTimelineToPDF = async (eventName: string, items: TimelineItem[]) => {
    if(isSharing) return ;
    isSharing=true;
  const htmlContent = `
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
          h1 { color: #4f46e5; margin-bottom: 5px; }
          .header { border-bottom: 2px solid #eee; padding-bottom: 20px; margin-bottom: 30px; }
          .item { margin-bottom: 20px; padding: 15px; border-left: 4px solid #4f46e5; background: #f9fafb; }
          .time { font-weight: bold; color: #4f46e5; font-size: 14px; }
          .activity { font-size: 18px; font-weight: bold; margin: 5px 0; }
          .desc { font-size: 14px; color: #666; }
          .status { font-size: 10px; text-transform: uppercase; font-weight: bold; margin-top: 5px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${eventName}</h1>
          <p>Official Event Timeline | Generated by EventFlow AI</p>
        </div>
        ${items.map(item => `
          <div class="item">
            <div class="time">${item.time}</div>
            <div class="activity">${item.activity}</div>
            <div class="desc">${item.description}</div>
            <div class="status">Status: ${item.status} | Responsible: ${item.responsible}</div>
          </div>
        `).join('')}
      </body>
    </html>
  `;

  try {
    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
  } catch (error) {
    console.error("Error generating Timeline PDF:", error);
  }finally{
    isSharing=false;
  }
};

/**
 * Exports Vendor Inventory to a professional PDF Report
 */
export const exportInventoryToPDF = async (items: any[]) => {
  const htmlContent = `
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
          h1 { color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th { background-color: #f3f4f6; text-align: left; padding: 12px; border: 1px solid #e5e7eb; color: #4b5563; }
          td { padding: 12px; border: 1px solid #e5e7eb; color: #1f2937; }
          .status-tag { font-weight: bold; padding: 4px 8px; border-radius: 4px; font-size: 12px; }
        </style>
      </head>
      <body>
        <h1>Inventory Report</h1>
        <p>Generated on: ${new Date().toLocaleDateString()}</p>
        <table>
          <thead>
            <tr>
              <th>Item Name</th>
              <th>Stock Level</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            ${items.map(i => `
              <tr>
                <td>${i.name}</td>
                <td>${i.stock} units</td>
                <td><span class="status-tag">${i.status}</span></td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </body>
    </html>
  `;

  try {
    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
  } catch (error) {
    console.error("Error generating Inventory PDF:", error);
  }
};